export const CATEGORIES = [
    {
        value: "Technology",
        label: "Technology",
        color: "bg-blue-100 text-blue-800 border-blue-200",
        hoverColor: "hover:bg-blue-200",
        icon: "💻",
    },
    {
        value: "Business",
        label: "Business",
        color: "bg-green-100 text-green-800 border-green-200",
        hoverColor: "hover:bg-green-200",
        icon: "💼",
    },
    {
        value: "Health",
        label: "Health",
        color: "bg-red-100 text-red-800 border-red-200",
        hoverColor: "hover:bg-red-200",
        icon: "🏥",
    },
    {
        value: "Lifestyle",
        label: "Lifestyle",
        color: "bg-purple-100 text-purple-800 border-purple-200",
        hoverColor: "hover:bg-purple-200",
        icon: "🌟",
    },
    {
        value: "Education",
        label: "Education",
        color: "bg-yellow-100 text-yellow-800 border-yellow-200",
        hoverColor: "hover:bg-yellow-200",
        icon: "📚",
    },
    {
        value: "Entertainment",
        label: "Entertainment",
        color: "bg-pink-100 text-pink-800 border-pink-200",
        hoverColor: "hover:bg-pink-200",
        icon: "🎭",
    },
    {
        value: "Travel",
        label: "Travel",
        color: "bg-indigo-100 text-indigo-800 border-indigo-200",
        hoverColor: "hover:bg-indigo-200",
        icon: "✈️",
    },
    {
        value: "Food",
        label: "Food",
        color: "bg-orange-100 text-orange-800 border-orange-200",
        hoverColor: "hover:bg-orange-200",
        icon: "🍳",
    },
    {
        value: "Sports",
        label: "Sports",
        color: "bg-emerald-100 text-emerald-800 border-emerald-200",
        hoverColor: "hover:bg-emerald-200",
        icon: "⚽",
    },
    {
        value: "General",
        label: "General",
        color: "bg-gray-100 text-gray-800 border-gray-200",
        hoverColor: "hover:bg-gray-200",
        icon: "📝",
    },
];
